### PR TITLE
Adding a first example

### PR DESCRIPTION
**Pull request by aentinger**

### CODE REVIEW

**Comment by aentinger** [comment]
Hi @per1234 :wave: May I ask you to add this example to CI build. If it's fine with you please just directly commit to this branch.

**Comment by per1234** [comment]
Done!

Since you only mentioned the example, I added just the "Compile Examples" and "Report Size Deltas" workflows. If you like, I can also add the rest of the workflows, as with the other 107-systems repos:
- [Spell Check](https://github.com/107-systems/107-Arduino-MCP2515/blob/master/.github/workflows/spell-check.yml)
- [Extra Library Checks](https://github.com/107-systems/107-Arduino-MCP2515/blob/master/.github/workflows/extra-library-checks.yml)
- [General Formatting Checks](https://github.com/107-systems/107-Arduino-MCP2515/blob/master/.github/workflows/general-formatting-checks.yml)

**Comment by aentinger** [comment]
Sorry, that was an oversight on my end. Please also add the other 3 checks you've mentioned.

**Comment by per1234** [comment]
OK, all done.

**Comment by aentinger** [comment]
Thank you 🚀

**Pull request merged**
